faqs:
  - question: What is Buk?
    answer: Buk is a revolutionary book sharing platform that connects readers, allows book exchanges, and helps you discover new literary adventures.
    
  - question: How does book sharing work?
    answer: Users can list books they're willing to share, request books from others, and arrange local or digital exchanges. Our platform ensures a safe and seamless sharing experience.
    
  - question: Is my personal information safe?
    answer: Absolutely! We use state-of-the-art encryption and never share your personal details without consent. Your privacy is our top priority.
    
  - question: Are there any fees?
    answer: Basic book sharing is completely free. We offer a premium membership with additional features like priority matching and extended community access.
    
  - question: How do I get started?
    answer: Simply download the app, create a profile, and start listing the books you're ready to share. Our intuitive interface makes book sharing simple and fun!