# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

books = [
    {"title": "To Kill a Mockingbird", "author": "Harper Lee"},
    {"title": "1984", "author": "George Orwell"},
    {"title": "Pride and Prejudice", "author": "Jane Austen"},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald"},
    {"title": "Moby Dick", "author": "Herman Melville"},
    {"title": "Brave New World", "author": "Aldous Huxley"},
    {"title": "The Catcher in the Rye", "author": "J.D. Salinger"},
    {"title": "The Hobbit", "author": "J.R.R. Tolkien"},
    {"title": "Fahrenheit 451", "author": "Ray Bradbury"},
    {"title": "Jane Eyre", "author": "Charlotte Bronte"},
    {"title": "War and Peace", "author": "Leo Tolstoy"},
    {"title": "The Odyssey", "author": "Homer"},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky"},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky"},
    {"title": "Wuthering Heights", "author": "Emily Bronte"},
    {"title": "The Divine Comedy", "author": "Dante Alighieri"},
    {"title": "Anna Karenina", "author": "Leo Tolstoy"},
    {"title": "The Lord of the Rings", "author": "J.R.R. Tolkien"},
    {"title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling"},
    {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde"},
    {"title": "Frankenstein", "author": "Mary Shelley"},
    {"title": "Dracula", "author": "Bram Stoker"},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel Garcia Marquez"},
    {"title": "The Sound and the Fury", "author": "William Faulkner"},
    {"title": "The Old Man and the Sea", "author": "Ernest Hemingway"},
    {"title": "The Kite Runner", "author": "Khaled Hosseini"},
    {"title": "A Tale of Two Cities", "author": "Charles Dickens"},
    {"title": "Les Misérables", "author": "Victor Hugo"},
    {"title": "Don Quixote", "author": "Miguel de Cervantes"},
    {"title": "Madame Bovary", "author": "Gustave Flaubert"},
    {"title": "The Count of Monte Cristo", "author": "Alexandre Dumas"},
    {"title": "The Alchemist", "author": "Paulo Coelho"},
    {"title": "Lolita", "author": "Vladimir Nabokov"},
    {"title": "The Handmaid's Tale", "author": "Margaret Atwood"},
    {"title": "Beloved", "author": "Toni Morrison"},
    {"title": "The Road", "author": "Cormac McCarthy"},
    {"title": "Life of Pi", "author": "Yann Martel"},
    {"title": "The Shining", "author": "Stephen King"},
    {"title": "Gone Girl", "author": "Gillian Flynn"},
    {"title": "A Game of Thrones", "author": "George R.R. Martin"},
    {"title": "Catch-22", "author": "Joseph Heller"},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck"},
    {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut"},
    {"title": "The Secret Garden", "author": "Frances Hodgson Burnett"},
    {"title": "Charlotte's Web", "author": "E.B. White"},
    {"title": "Of Mice and Men", "author": "John Steinbeck"},
    {"title": "The Giver", "author": "Lois Lowry"},
    {"title": "The Hunger Games", "author": "Suzanne Collins"},
    {"title": "The Fault in Our Stars", "author": "John Green"},
    {"title": "Dune", "author": "Frank Herbert"},
    {"title": "The Hitchhiker's Guide to the Galaxy", "author": "Douglas Adams"},
    {"title": "The Chronicles of Narnia", "author": "C.S. Lewis"},
    {"title": "Memoirs of a Geisha", "author": "Arthur Golden"},
    {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson"},
    {"title": "The Da Vinci Code", "author": "Dan Brown"},
    {"title": "The Catcher in the Rye", "author": "J.D. Salinger"},
    {"title": "1984", "author": "George Orwell"},
    {"title": "To Kill a Mockingbird", "author": "Harper Lee"},
    {"title": "Brave New World", "author": "Aldous Huxley"},
    {"title": "Animal Farm", "author": "George Orwell"},
    {"title": "Moby Dick", "author": "Herman Melville"},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald"},
    {"title": "The Scarlet Letter", "author": "Nathaniel Hawthorne"},
    {"title": "Pride and Prejudice", "author": "Jane Austen"},
    {"title": "Jane Eyre", "author": "Charlotte Bronte"},
    {"title": "Wuthering Heights", "author": "Emily Bronte"},
    {"title": "The Odyssey", "author": "Homer"},
    {"title": "The Iliad", "author": "Homer"},
    {"title": "War and Peace", "author": "Leo Tolstoy"},
    {"title": "Anna Karenina", "author": "Leo Tolstoy"},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky"},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky"},
    {"title": "The Divine Comedy", "author": "Dante Alighieri"},
    {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde"},
    {"title": "Les Misérables", "author": "Victor Hugo"},
    {"title": "The Count of Monte Cristo", "author": "Alexandre Dumas"},
    {"title": "Don Quixote", "author": "Miguel de Cervantes"},
    {"title": "A Tale of Two Cities", "author": "Charles Dickens"},
    {"title": "Great Expectations", "author": "Charles Dickens"},
    {"title": "The Old Man and the Sea", "author": "Ernest Hemingway"},
    {"title": "The Sun Also Rises", "author": "Ernest Hemingway"},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel Garcia Marquez"},
    {"title": "Love in the Time of Cholera", "author": "Gabriel Garcia Marquez"},
    {"title": "The Road", "author": "Cormac McCarthy"},
    {"title": "Beloved", "author": "Toni Morrison"},
    {"title": "The Bluest Eye", "author": "Toni Morrison"},
    {"title": "Song of Solomon", "author": "Toni Morrison"},
    {"title": "Invisible Man", "author": "Ralph Ellison"},
    {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut"},
    {"title": "Catch-22", "author": "Joseph Heller"},
    {"title": "Gone with the Wind", "author": "Margaret Mitchell"},
    {"title": "Dracula", "author": "Bram Stoker"},
    {"title": "Frankenstein", "author": "Mary Shelley"},
    {"title": "The Shining", "author": "Stephen King"},
    {"title": "It", "author": "Stephen King"},
    {"title": "The Stand", "author": "Stephen King"},
]